
/********************************************************/
-- C O N E X I Ó N 
/********************************************************/
-- Base de Datos : agropach_bd
-- Usuario	 	 : localhost(root)
-- Contraseña	 : agropach_peru21

/********************************************************/
-- Tabla: MAE_USUARIO 
/********************************************************/
CREATE TABLE IF NOT EXISTS MAE_USUARIO (
  ID_USUARIO 		VARCHAR(8) 		NOT NULL,
  NOMBRE 			VARCHAR(150) 	NOT NULL,
  EMAIL 			VARCHAR(60),
  CLAVE 			VARCHAR(60) 	NOT NULL,
  IMAGEN 			VARCHAR(150),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MAE_USUARIO
  ADD PRIMARY KEY (ID_USUARIO);
  
-- Poblar usuarios
INSERT INTO MAE_USUARIO (V_COD_USER, V_NOMBRE, V_EMAIL, V_CLAVE, V_IMAGEN, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
('admweb', 'Johnny Reque', 'johnnyreque@gmail.com','jreque21', 'admweb.jpg', '1', 'admweb', CURRENT_TIMESTAMP);

/********************************************************/
-- Tabla: MAE_UNIDAD
/********************************************************/ 
CREATE TABLE IF NOT EXISTS MAE_UNIDAD (
  ID_UNIDAD			INT(4) 			UNSIGNED ZEROFILL NOT NULL,
  NOMBRE 			VARCHAR(150) 	NOT NULL,
  ABREVIATURA		VARCHAR(10) 	NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB 	DEFAULT CHARSET=utf8;
ALTER TABLE MAE_UNIDAD
  ADD PRIMARY KEY (ID_UNIDAD);
ALTER TABLE MAE_UNIDAD
  ADD CONSTRAINT FK_UNIDAD_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE MAE_UNIDAD
  MODIFY ID_UNIDAD INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT;
  

/********************************************************/
-- Tabla: MAE_TIPODOC
/********************************************************/ 
CREATE TABLE IF NOT EXISTS MAE_TIPODOC (
  ID_TIPODOC		VARCHAR(4) 		NOT NULL,
  DES_CORTA			VARCHAR(100) 	NOT NULL,
  DES_LARGA			VARCHAR(150) 	NOT NULL,
  LONGITUD			INT(3) 			NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB 	DEFAULT CHARSET=utf8;
ALTER TABLE MAE_TIPODOC
  ADD PRIMARY KEY (ID_TIPODOC);
ALTER TABLE MAE_TIPODOC
  ADD CONSTRAINT FK_TIPODOC_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);

  
/********************************************************/
-- Tabla: MAE_ROL
/********************************************************/
CREATE TABLE IF NOT EXISTS MAE_ROL (
  ID_ROL 			VARCHAR(10) 	NOT NULL,
  DES_CORTA			VARCHAR(100) 	NOT NULL,
  DES_LARGA			VARCHAR(150) 	NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MAE_ROL
  ADD PRIMARY KEY (ID_ROL);
ALTER TABLE MAE_ROL
  ADD CONSTRAINT FK_ROL_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);

-- Poblar Rol
INSERT INTO MAE_ROL VALUES ('WEB_MASTER', 'ADMINISTRADOR WEB', 'ADMINISTRADOR DEL SISTEMA', '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
  
/********************************************************/
-- Tabla: MAE_PRODUCTO
/********************************************************/
CREATE TABLE IF NOT EXISTS MAE_PRODUCTO (
  ID_PRODUCTO 		VARCHAR(8) 		NOT NULL,
  NOMBRE			VARCHAR(150) 	NOT NULL,
  DESCRIPCION		TEXT,
  ID_UNIDAD			INT(4)			UNSIGNED NOT NULL,
  PRECIO_UNITARIO  	DECIMAL(9,2) 	DEFAULT 0,
  IMAGEN			VARCHAR(100),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB 	DEFAULT CHARSET=utf8;
ALTER TABLE MAE_PRODUCTO
  ADD PRIMARY KEY (ID_PRODUCTO);
ALTER TABLE MAE_PRODUCTO
  ADD CONSTRAINT FK_PRODUCTO_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE MAE_PRODUCTO
  ADD CONSTRAINT FK_PRODUCTO_UND FOREIGN KEY (ID_UNIDAD) REFERENCES MAE_UNIDAD(ID_UNIDAD);

  
/********************************************************/
-- Tabla: MAE_CLIENTE
/********************************************************/
CREATE TABLE IF NOT EXISTS MAE_CLIENTE (
  ID_CLIENTE 		INT(8) 			UNSIGNED ZEROFILL NOT NULL,
  RAZON_SOCIAL		VARCHAR(150)	NOT NULL,
  NOM_COMERCIAL		VARCHAR(150),
  DIRECCION			VARCHAR(150),
  ID_TIPODOC		VARCHAR(4),			
  NUM_DOCUMENTO    	VARCHAR(30),
  WEB				VARCHAR(100),
  EMAIL 			VARCHAR(60),
  TELEFONO1			VARCHAR(20),
  TELEFONO2			VARCHAR(20),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB 	DEFAULT CHARSET=utf8;
ALTER TABLE MAE_CLIENTE
  ADD PRIMARY KEY (ID_CLIENTE);
ALTER TABLE MAE_CLIENTE
  ADD CONSTRAINT FK_PROVEEDOR_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE MAE_CLIENTE
  ADD CONSTRAINT FK_PROVEEDOR_TIPODOC FOREIGN KEY (ID_TIPODOC) REFERENCES MAE_TIPODOC(ID_TIPODOC);
ALTER TABLE MAE_CLIENTE
  MODIFY ID_CLIENTE INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT;
  

/********************************************************/
-- Tabla: Nivel del Menú
/********************************************************/
CREATE TABLE IF NOT EXISTS NIVEL (
  ID_NIVEL 			INT(3) 			UNSIGNED ZEROFILL NOT NULL,
  DESCRIPCION		VARCHAR(150) 	NOT NULL,
  ICONO 			VARCHAR(150) 	NULL,
  ORDEN 			INT(3) 			NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE NIVEL
  ADD PRIMARY KEY (ID_NIVEL);
ALTER TABLE NIVEL
  ADD CONSTRAINT FK_NIVEL_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE NIVEL
  MODIFY ID_NIVEL INT(3) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT;
  
-- Poblar niveles
INSERT INTO NIVEL (ID_NIVEL, DESCRIPCION, ICONO, ORDEN, FLAG_ESTADO, AUD_USR_REG, AUD_FEC_REG) VALUES
(001, 'Operaciones', 'fa fa-globe', 1, '1', 'admweb', CURRENT_TIMESTAMP),
(002, 'Reportes', 'fa fa-dashboard', 2, '1', 'admweb', CURRENT_TIMESTAMP),
(003, 'Tablas', 'fa fa-table', 3, '1', 'admweb', CURRENT_TIMESTAMP),
(004, 'Seguridad', 'fa fa-user', 4, '1', 'admweb', CURRENT_TIMESTAMP);


-- DML - TKD
-- Poblar usuarios
INSERT INTO MAE_USUARIO (V_COD_USER, V_NOMBRE, V_EMAIL, V_CLAVE, V_IMAGEN, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
('admweb', 'Johnny Reque', 'johnnyreque@gmail.com','jreque21', 'admweb.jpg', '1', 'admweb', CURRENT_TIMESTAMP);

-- Poblar niveles
INSERT INTO MAE_MENU_NIVEL (N_COD_NIVEL, V_NOMBRE, V_ICONO, N_ORDEN, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(001, 'Administracion', 'fa fa-globe', 1, '1', 'admweb', CURRENT_TIMESTAMP),
(002, 'Asistencia', 'fa fa-globe', 2, '1', 'admweb', CURRENT_TIMESTAMP),
(003, 'Aprendizaje', 'fa fa-globe', 3, '1', 'admweb', CURRENT_TIMESTAMP),
(004, 'Eventos', 'fa fa-globe', 4, '1', 'admweb', CURRENT_TIMESTAMP),
(005, 'Externos', 'fa fa-globe', 5, '1', 'admweb', CURRENT_TIMESTAMP),
(006, 'Reportes', 'fa fa-dashboard', 6, '1', 'admweb', CURRENT_TIMESTAMP),
(007, 'Academia', 'fa fa-dashboard', 7, '1', 'admweb', CURRENT_TIMESTAMP),
(008, 'Maestros', 'fa fa-table', 8, '1', 'admweb', CURRENT_TIMESTAMP),
(009, 'Seguridad', 'fa fa-user', 9, '1', 'admweb', CURRENT_TIMESTAMP);

-- Pobar opciones
INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(1, 1, 'Estudiante', 'ESTUDIANTE','mae_estudiante_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(1, 2, 'Horario', 'HORARIO','mov_horario_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP)
(1, 3, 'Horario-Clase', 'HORARIO - CLASE','mov_clase_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP)
(1, 4, 'Matricula', 'MATRICULA','mov_matricula_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP)
(1, 5, 'Pago', 'PAGO','mov_pago_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(2, 1, 'Registro', 'ASISTENCIA','mov_asistencia_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(2, 2, 'Hoja Diaria', 'ASISTENCIA DIARIA','rpt_asistencia_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(3, 1, 'Promocion', 'PROMOCION','mae_promocion_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(3, 2, 'Promocionado', 'PROMOCIONADO','mae_promocionado_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(3, 3, 'Graduado', 'GRADUADO','mae_graduado_lista.php', 'fa fa-cogs', '0', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(4, 1, 'Evento', 'EVENTO','mae_evento_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(4, 2, 'Invitado', 'INVITADO','mae_invitado_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(4, 3, 'Asistente', 'ASISTENTE','mae_asistente_lista.php', 'fa fa-cogs', '0', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(5, 1, 'Promocion', 'PROMOCION EXTERNA','mae_promocionext_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(5, 2, 'Promocionado', 'PROMOCIONADO EXTERNO','mae_promocionadoext_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(5, 3, 'Graduado', 'GRADUADO EXTERNO','mae_graduadoext_lista.php', 'fa fa-cogs', '0', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(7, 1, 'Empresa', 'EMPRESA','mae_empresa_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(7, 2, 'Sedes', 'SEDE','mae_sede_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(7, 3, 'Instructor', 'INSTRUCTOR','mae_instructor_lista.php', 'fa fa-cogs', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(7, 4, 'Instructor-Sede', 'INSTRUCTOR - SEDE','mae_instructorsede_lista.php', 'fa fa-key', '1', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(8, 1, 'Tipo Documento', 'TIPO DE DOCUMENTO', 'mae_tipodoc_lista.php', 'fa fa-file-o', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 2, 'Moneda', 'MONEDA', 'mae_moneda_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 3, 'Forma Pago', 'FORMA DE PAGO', 'mae_formapago_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 4, 'Medio Pago', 'MEDIO DE PAGO', 'mae_mediopago_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 5, 'Tipo Grado', 'TIPO DE GRADO', 'mae_tipogrado_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 6, 'Cinturonn', 'CINTURON', 'mae_cinturon_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 7, 'Turnos', 'TURNO', 'mae_turno_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 8, 'Tipo Asistencia', 'TIPO ASISTENCIA', 'mae_tipoasis_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(8, 9, 'Tarifas', 'TARIFAS', 'mae_tarifa_lista.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP);

INSERT INTO MAE_MENU_OPCION (N_COD_NIVEL, N_ORDEN, V_NOMBRE, V_ETIQUETA, V_URL, V_ICONO, V_FLAG_PERMISO, V_FLAG_ESTADO, V_AUD_USR_REG, D_AUD_FEC_REG) VALUES
(9, 1, 'Usuarios', 'USUARIO','mae_usuario_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(9, 2, 'Roles', 'ROLES','mae_rol_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(9, 3, 'Rol-Usuario', 'ROL - USUARIO','mae_rolusuario_lista.php', 'fa fa-cogs', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(9, 4, 'Permisos', 'PERMISOS','mae_rolopcion_lista.php', 'fa fa-key', '1', '1', 'admweb', CURRENT_TIMESTAMP);

/********************************************************/
-- Tabla: Opción para nivel del Menú
/********************************************************/
CREATE TABLE IF NOT EXISTS OPCION (
  ID_OPCION 		INT(3) 			UNSIGNED ZEROFILL NOT NULL,
  ID_NIVEL			INT(3) 			UNSIGNED NOT NULL,
  ORDEN 			INT(3) 			NOT NULL,
  NOMBRE			VARCHAR(150) 	NULL,
  ETIQUETA			VARCHAR(150) 	NULL,
  URL				VARCHAR(150) 	NULL,
  ICONO 			VARCHAR(150) 	NULL,
  FLAG_PERMISO  	CHAR(1) 		DEFAULT '1' NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPCION
  ADD PRIMARY KEY (ID_OPCION);
ALTER TABLE OPCION
  ADD CONSTRAINT FK_OPCION_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE OPCION
  ADD CONSTRAINT FK_OPCION_NIVEL FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL (ID_NIVEL);
ALTER TABLE OPCION
  MODIFY ID_OPCION INT(3) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT;

-- Pobar opciones
INSERT INTO OPCION (ID_OPCION, ID_NIVEL, ORDEN, NOMBRE, ETIQUETA, URL, ICONO, FLAG_PERMISO, FLAG_ESTADO, AUD_USR_REG, AUD_FEC_REG) VALUES
(001, 1, 1, 'Registro de Venta', 'VENTA', 'venta_lista.php', 'fa fa-file-o', '1', '1', 'admweb', CURRENT_TIMESTAMP),

(002, 2, 1, 'Reporte de Ventas', 'REPORTE VENTAS', 'ventas_reporte.php', 'fa fa-line-chart', '1', '1', 'admweb', CURRENT_TIMESTAMP),

(003, 3, 1, 'Productos', 'PRODUCTO','producto_lista.php', 'fa fa-cart-plus', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(004, 3, 2, 'Clientes', 'CLIENTE','cliente_lista.php', 'fa fa-handshake-o', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(005, 3, 3, 'Unidad', 'UNIDAD','unidad_lista.php', 'fa fa-bitcoin', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(006, 3, 4, 'Tipo Documento', 'TIPO DOCUMENTO','tipodoc_lista.php', 'fa fa-copy', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(007, 3, 5, 'Numerador B.V.', 'NUMERADOR B.V','numerador_lista.php', 'fa fa-sort-numeric-asc', '0', '1', 'admweb', CURRENT_TIMESTAMP),

(008, 4, 1, 'Usuarios', 'USUARIO','usuario_lista.php', 'fa fa-group', '1', '1', 'admweb', CURRENT_TIMESTAMP),
(009, 4, 2, 'Roles', 'ROLES','rol_lista.php', 'fa fa-briefcase', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(010, 4, 3, 'Rol-Usuario', 'ROL USUARIO','rolusuario_lista.php', 'fa fa-cogs', '0', '1', 'admweb', CURRENT_TIMESTAMP),
(011, 4, 4, 'Permisos', 'PERMISOS','rolopcion_lista.php', 'fa fa-key', '1', '1', 'admweb', CURRENT_TIMESTAMP);


/********************************************************/
-- Tabla: MAE_ROL_USUARIO
/********************************************************/
CREATE TABLE IF NOT EXISTS MAE_ROL_USUARIO (
  ID_ROL 			VARCHAR(10) 	NOT NULL,
  ID_USUARIO 		VARCHAR(8) 		NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MAE_ROL_USUARIO
  ADD PRIMARY KEY (ID_ROL, ID_USUARIO);
ALTER TABLE MAE_ROL_USUARIO
  ADD CONSTRAINT FK_ROLUSR_ROL FOREIGN KEY (ID_ROL) REFERENCES MAE_ROL (ID_ROL);
ALTER TABLE MAE_ROL_USUARIO
  ADD CONSTRAINT FK_ROLUSR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE MAE_ROL_USUARIO
  ADD CONSTRAINT FK_ROLUSR_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
  
-- Poblar Rol-USUARIO
INSERT INTO MAE_ROL_USUARIO VALUES ('WEB_MASTER', 'admweb', '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
  
/********************************************************/
-- Tabla: MAE_ROL_OPCION
/********************************************************/
CREATE TABLE IF NOT EXISTS MAE_ROL_OPCION (
  ID_ROL 			VARCHAR(10) 	NOT NULL,
  ID_OPCION 		INT(3) 			UNSIGNED NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MAE_ROL_OPCION
  ADD PRIMARY KEY (ID_ROL, ID_OPCION);
ALTER TABLE MAE_ROL_OPCION
  ADD CONSTRAINT FK_ROLOPC_ROL FOREIGN KEY (ID_ROL) REFERENCES MAE_ROL (ID_ROL);
ALTER TABLE MAE_ROL_OPCION
  ADD CONSTRAINT FK_ROLOPC_OPC FOREIGN KEY (ID_OPCION) REFERENCES OPCION (ID_OPCION);
ALTER TABLE MAE_ROL_OPCION
  ADD CONSTRAINT FK_ROLOPC_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);

-- Poblar Rol-Opción
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 3, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 4, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 5, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 6, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 7, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 8, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 9, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 10, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);
INSERT INTO `MAE_ROL_OPCION` VALUES ('WEB_MASTER', 11, '1', 'admweb', CURRENT_TIMESTAMP, NULL, NULL);

/********************************************************/
-- Tabla: MAE_NUMERADOR_DOC
/********************************************************/ 
CREATE TABLE IF NOT EXISTS MAE_NUMERADOR_DOC (
  ID_DOCUMENTO		VARCHAR(4) 		NOT NULL,
  SERIE 			VARCHAR(4) 		NOT NULL,
  CORRELATIVO		INT(8) 			UNSIGNED NOT NULL,
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB 	DEFAULT CHARSET=utf8;
ALTER TABLE MAE_NUMERADOR_DOC
  ADD PRIMARY KEY (ID_DOCUMENTO, SERIE);
ALTER TABLE MAE_NUMERADOR_DOC
  ADD CONSTRAINT FK_NUMDOC_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
    
  
/********************************************************/
-- Tabla: OPE_VENTA_CAB
/********************************************************/  
CREATE TABLE IF NOT EXISTS OPE_VENTA_CAB (
  ID_OPERACION 		INT(10) 		UNSIGNED ZEROFILL NOT NULL,
  ID_DOCUMENTO		VARCHAR(4) 		NOT NULL,
  SERIE 			VARCHAR(4) 		NOT NULL,
  CORRELATIVO		INT(8)			UNSIGNED NOT NULL,
  ID_CLIENTE 		INT(8) 			UNSIGNED NOT NULL,
  FEC_VENTA   		DATETIME		NOT NULL,  
  TIPO_PAGO   		CHAR(1)			DEFAULT '1' NOT NULL,
  IMP_TOTAL 		DECIMAL(9,2),
  IMP_PAGADO		DECIMAL(9,2),
  IMP_PORPAGAR 		DECIMAL(9,2),  
  ID_OPERACION_REF	INT(10) 		UNSIGNED,    
  IMP_AMORTIZACION	DECIMAL(9,2),
  OBSERVACION   	TEXT,  
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPE_VENTA_CAB
  ADD CONSTRAINT PK_OPE_VENTA_CAB PRIMARY KEY (ID_OPERACION);
ALTER TABLE OPE_VENTA_CAB
  ADD CONSTRAINT FK_OPEVENTA_DOC FOREIGN KEY (ID_DOCUMENTO, SERIE) REFERENCES MAE_NUMERADOR_DOC (ID_DOCUMENTO, SERIE);
ALTER TABLE OPE_VENTA_CAB
  ADD CONSTRAINT FK_OPEVENTA_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES MAE_CLIENTE (ID_CLIENTE);
ALTER TABLE OPE_VENTA_CAB
  ADD CONSTRAINT FK_OPEVENTA_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
ALTER TABLE OPE_VENTA_CAB
  MODIFY ID_OPERACION INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT;
  
  
/********************************************************/
-- Tabla: OPE_VENTA_DET
/********************************************************/  
CREATE TABLE IF NOT EXISTS OPE_VENTA_DET (
  ID_OPERACION 		INT(10) 		UNSIGNED NOT NULL,
  ID_ITEM 			INT(3) 			UNSIGNED NOT NULL,
  ID_PRODUCTO 		VARCHAR(8) 		NOT NULL,
  CANTIDAD 			DECIMAL(9,2),
  PESO 				DECIMAL(9,2),
  PRECIO_UNITARIO 	DECIMAL(9,2),
  IMP_SUBTOTAL 		DECIMAL(9,2),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPE_VENTA_DET
  ADD PRIMARY KEY (ID_OPERACION, ID_ITEM);
ALTER TABLE OPE_VENTA_DET
  ADD CONSTRAINT FK_OPEVENTAD_CAB FOREIGN KEY (ID_OPERACION) REFERENCES OPE_VENTA_CAB (ID_OPERACION);
ALTER TABLE OPE_VENTA_DET
  ADD CONSTRAINT FK_OPEVENTAD_PROD FOREIGN KEY (ID_PRODUCTO) REFERENCES MAE_PRODUCTO (ID_PRODUCTO);
ALTER TABLE OPE_VENTA_DET
  ADD CONSTRAINT FK_OPEVENTAD_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
  

/********************************************************/
-- Tabla: SAL_VENTA_PORCOBRAR
/********************************************************/  
CREATE TABLE IF NOT EXISTS SAL_CTA_COBRAR (
  ID_OPERACION 		INT(10) 		UNSIGNED NOT NULL,  
  ID_CLIENTE 		INT(8) 			NOT NULL,
  IMP_PENDIENTE 	DECIMAL(9,2),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE SAL_CTA_COBRAR
  ADD PRIMARY KEY (ID_OPERACION);
ALTER TABLE SAL_CTA_COBRAR
  ADD CONSTRAINT FK_SALDOVENTA_OPE FOREIGN KEY (ID_OPERACION) REFERENCES OPE_VENTA_CAB (ID_OPERACION);
ALTER TABLE SAL_CTA_COBRAR
  ADD CONSTRAINT FK_SALDOVENTA_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
  
  
  
  
/********************************************************/
-- Tabla: OPE_CTAXCOBRAR
/********************************************************/  
CREATE TABLE IF NOT EXISTS OPE_CTAXCOBRAR (
  ID_OPERACION 		INT(10) 		UNSIGNED NOT NULL,  
  ID_CLIENTE 		INT(8) 			NOT NULL,
  IMP_PORCOBRAR		DECIMAL(9,2),
  IMP_PAGADO 		DECIMAL(9,2),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPE_CTAXCOBRAR
  ADD PRIMARY KEY (ID_OPERACION);
ALTER TABLE OPE_CTAXCOBRAR
  ADD CONSTRAINT FK_CTAXCOBRAR_OPE FOREIGN KEY (ID_OPERACION) REFERENCES OPE_VENTA_CAB (ID_OPERACION);
ALTER TABLE OPE_CTAXCOBRAR
  ADD CONSTRAINT FK_CTAXCOBRAR_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);

/********************************************************/
-- Tabla: OPE_CTAXCOBRAR_MOV
/********************************************************/  
CREATE TABLE IF NOT EXISTS OPE_CTAXCOBRAR_MOV (
  ID_OPERACION 		INT(10) 		UNSIGNED NOT NULL, 
  ID_MOV 			INT(3) 			UNSIGNED NOT NULL,
  FEC_VALOR   		DATETIME		NOT NULL,
  IMP_INICIAL		DECIMAL(9,2),
  IMP_PAGADO 		DECIMAL(9,2),
  IMP_FINAL			DECIMAL(9,2),
  ID_NRO_PAGO_REF	INT(10),  
  ID_ITEM_REF		INT(3),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPE_CTAXCOBRAR_MOV
  ADD PRIMARY KEY (ID_OPERACION, ID_MOV);
ALTER TABLE OPE_CTAXCOBRAR_MOV
  ADD CONSTRAINT FK_CTAXCOBRAR_MOV FOREIGN KEY (ID_OPERACION) REFERENCES OPE_CTAXCOBRAR (ID_OPERACION);
ALTER TABLE OPE_CTAXCOBRAR_MOV
  ADD CONSTRAINT FK_CTAXCOBRAR_MOV_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);
  
/********************************************************/
-- Tabla: OPE_CXC_PAGO
/********************************************************/  
CREATE TABLE IF NOT EXISTS OPE_CXC_PAGO (
  ID_NRO_PAGO		INT(10) 		UNSIGNED NOT NULL, 
  FEC_PAGO   		DATETIME		NOT NULL,  
  IMP_TOTAL 		DECIMAL(9,2),
  OBSERVACION   	TEXT,  
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPE_CXC_PAGO
  ADD PRIMARY KEY (ID_NRO_PAGO);
ALTER TABLE OPE_CXC_PAGO
  ADD CONSTRAINT FK_CXC_PAGO_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);

/********************************************************/
-- Tabla: OPE_CXC_PAGO_DET
/********************************************************/  
CREATE TABLE IF NOT EXISTS OPE_CXC_PAGO_DET (
  ID_NRO_PAGO		INT(10) 		UNSIGNED NOT NULL,  
  ID_ITEM 			INT(3) 			UNSIGNED NOT NULL,
  ID_OPERACION 		INT(10),  
  IMP_PAGADO 		DECIMAL(9,2),
  FLAG_ESTADO   	CHAR(1) 		DEFAULT '1' NOT NULL,
  AUD_USR_REG 		VARCHAR(8) 		NOT NULL,
  AUD_FEC_REG   	DATETIME 		NOT NULL,
  AUD_USR_MOD 		VARCHAR(8) 		NULL,
  AUD_FEC_MOD   	DATETIME 		NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE OPE_CXC_PAGO_DET
  ADD PRIMARY KEY (ID_NRO_PAGO, ID_ITEM);
ALTER TABLE OPE_CXC_PAGO_DET
  ADD CONSTRAINT FK_CXC_PAGO_DET FOREIGN KEY (ID_NRO_PAGO) REFERENCES OPE_CXC_PAGO (ID_NRO_PAGO);
ALTER TABLE OPE_CXC_PAGO_DET
  ADD CONSTRAINT FK_CXC_PAGO_DET_USR FOREIGN KEY (AUD_USR_REG) REFERENCES MAE_USUARIO (ID_USUARIO);